site_name: My Docs
site_name: PS Documentations
#site_url: https://james-willett.github.io/mkdocs-material-youtube-tutorial/
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: slate
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to light mode
      primary: teal
      accent: amber
    - scheme: default 
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode    
      primary: teal
      accent: purple

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/spawan07
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2023 <a href="https://github.com/spawan07"  target="_blank" rel="noopener">Pawan Sharma</a>